{% set base_name = "libignition-plugin" %}
{% set version = "1.4.0" %}
{% set major_version = version.split('.')[0] %}
{% set name = base_name + major_version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-plugin/archive/ignition-plugin_{{ version }}.tar.gz
    sha256: 504c6ef66d48342d92ec7b227a134485ae79946df16094843f33d80f9af34e08

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libignition-cmake2
    - libignition-tools1
    - dlfcn-win32  # [win]
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/plugin{{ major_version }}/ignition/plugin.hh  # [not win]
    - test -f ${PREFIX}/lib/ruby/ignition/cmdplugin{{ major_version }}.rb  # [not win]
    - if not exist %PREFIX%\\Library\\include\\ignition\plugin{{ major_version }}\ignition\plugin.hh exit 1  # [win]
    # Disabled due to https://github.com/conda-forge/libignition-plugin-feedstock/issues/13
    # - if not exist %PREFIX%\\Library\\lib\\ruby\\ignition\\cmdplugin{{ major_version }}.rb exit 1  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-plugin
  license: Apache-2.0
  license_file: COPYING
  summary: |
    Ignition Plugin is a component in the ignition framework, a set of libraries designed 
    to rapidly develop robot applications.

extra:
  recipe-maintainers:
    - seanyen
    - traversaro
